### ISSUE TITLE
Price by date

### ISSUE THREAD

**Issue by TheYahya** [b00f/bitcoin_annually_analyse#3]
Hi @b00f 
Isn't it a good idea to have a function that give us bitcoin price by date?

**Comment by b00f** [comment]
Actually I had an idea that bitcoin price is usually down at the beginning of the year and it is high at the end of year. However the result didn't show it. 
compare monthly report at  2015 and 2016.
As I understood here, there is no rule for bit coin price. No one can predict it.

What do you want to extract from daily report?
consider that daily report is going to be very messy.

**Comment by TheYahya** [comment]
Yeah, you're right, but I mean a function that give us bitcoin price in a specific day. there's no need to printing it. It could be another module/repo too.
I just wrote a [npm package](https://github.com/TheYahya/bitcoin-price-by-date) for this functionality.

**Comment by b00f** [comment]
Yahya, Great job. It is a good idea. go ahead.

**Comment by b00f** [comment]
Do you want to change anything here? or I close this issue?

**Comment by TheYahya** [comment]
Ok, so I will send a PR.

**Comment by b00f** [comment]
Your project is better than mine, You keep it alive. I will terminate it soon.

**Comment by b00f** [comment]
If you can support monthly and yearly report it will be asome

**Comment by TheYahya** [comment]
Thank you, sure, I will 👍

**Comment by TheYahya** [comment]
I think you should make it a pip module too.

**Comment by b00f** [comment]
pip module? I didn't use it before.... 
please check this PR: https://github.com/b00f/bitcoin_annually_analyse/pull/4

**Comment by TheYahya** [comment]
[pip](https://en.wikipedia.org/wiki/Pip_(package_manager)) is a package manager for python, like npm in for node.

And [this](https://python-packaging.readthedocs.io/en/latest/) is a good reference to start with.

**Comment by b00f** [comment]
Ah, I know about it. I worked with it before. thanks
